on:
  release:
    types: [published, edited]
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
      
      - id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/bolu61/devcontainer
      
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - uses: docker/build-push-action@v3
        with:
          push: true
          file: "{{context}}/containerfile"
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
